// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR6U3cKYXUN2lcoBz1Gaz1Gpv0IS4LfUA',
    appId: '1:859694487026:web:970d5a4e61234ef4dac76b',
    messagingSenderId: '859694487026',
    projectId: 'platzi-d7bd9',
    authDomain: 'platzi-d7bd9.firebaseapp.com',
    storageBucket: 'platzi-d7bd9.appspot.com',
    measurementId: 'G-DMBLW6WFN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7JfTGVBDg9HTpnXn8igDjmp1YP6G5MP0',
    appId: '1:859694487026:android:7b16eb0189937fafdac76b',
    messagingSenderId: '859694487026',
    projectId: 'platzi-d7bd9',
    storageBucket: 'platzi-d7bd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSqhJ-WD3PBzpz6PQzXBuJdI-wE5dJsyI',
    appId: '1:859694487026:ios:a84daf6b754c69e2dac76b',
    messagingSenderId: '859694487026',
    projectId: 'platzi-d7bd9',
    storageBucket: 'platzi-d7bd9.appspot.com',
    iosBundleId: 'com.example.platzi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSqhJ-WD3PBzpz6PQzXBuJdI-wE5dJsyI',
    appId: '1:859694487026:ios:a84daf6b754c69e2dac76b',
    messagingSenderId: '859694487026',
    projectId: 'platzi-d7bd9',
    storageBucket: 'platzi-d7bd9.appspot.com',
    iosBundleId: 'com.example.platzi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR6U3cKYXUN2lcoBz1Gaz1Gpv0IS4LfUA',
    appId: '1:859694487026:web:fca35215086d2b9edac76b',
    messagingSenderId: '859694487026',
    projectId: 'platzi-d7bd9',
    authDomain: 'platzi-d7bd9.firebaseapp.com',
    storageBucket: 'platzi-d7bd9.appspot.com',
    measurementId: 'G-BWS05H50FB',
  );
}
